import type { Metadata } from "next";
import { Stick } from "next/font/google";
import "./styles/globals.css";


{/*フォントは必要の時にhttps://fonts.google.com/?lang=ja_Jpanから確認すること */}


const stick_font = Stick({
  subsets: ["latin"],
  variable: "--font-stick",
  display: "swap",
  weight: ["400"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${stick_font.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
